"""Synthetic hand gesture sequence generator.

Produces [seq_len, 63] float32 arrays (x,y,z for 21 MediaPipe landmarks,
wrist-relative and palm-size normalised) — the same format that
FeatureExtractor.extract_coordinates() would produce on live data.

How it works
------------
1. OPEN_PALM  and FIST are hard-coded canonical poses derived from typical
   MediaPipe output (wrist at origin, palm-size = 1.0).
2. Every other gesture is built by interpolating each finger between the
   extended and curled positions using per-finger curl weights.
3. Temporal sequences are generated by:
     a. Optionally blending two related poses over time (dynamic gestures).
     b. Adding Ornstein-Uhlenbeck correlated noise per joint per axis to
        simulate natural hand tremor.
     c. Applying a slow random global drift (smooth random-walk in SO(3)).
4. Random per-sample augmentation (rotation, scale, noise level, speed) is
   baked in so every call to generate_sequence() returns a unique sample.
"""
from __future__ import annotations

import numpy as np

# ---------------------------------------------------------------------------
# Canonical poses — [21, 3]  (x, y, z)
# Coordinate system: wrist at origin; -y = toward fingertips;
# +z = toward viewer; units in palm-size (wrist→middle-MCP distance = 1.0)
# ---------------------------------------------------------------------------

OPEN_PALM = np.array([
    [ 0.000,  0.000,  0.000],  # 0  Wrist
    [ 0.275, -0.195,  0.025],  # 1  Thumb CMC
    [ 0.448, -0.350,  0.022],  # 2  Thumb MCP
    [ 0.570, -0.510,  0.010],  # 3  Thumb IP
    [ 0.660, -0.665,  0.000],  # 4  Thumb Tip
    [ 0.215, -0.760,  0.000],  # 5  Index MCP
    [ 0.215, -1.050, -0.018],  # 6  Index PIP
    [ 0.215, -1.250, -0.035],  # 7  Index DIP
    [ 0.215, -1.440, -0.050],  # 8  Index Tip
    [ 0.018, -0.815,  0.000],  # 9  Middle MCP
    [ 0.018, -1.120, -0.020],  # 10 Middle PIP
    [ 0.018, -1.340, -0.038],  # 11 Middle DIP
    [ 0.018, -1.555, -0.055],  # 12 Middle Tip
    [-0.175, -0.760,  0.000],  # 13 Ring MCP
    [-0.175, -1.050, -0.018],  # 14 Ring PIP
    [-0.175, -1.250, -0.035],  # 15 Ring DIP
    [-0.175, -1.440, -0.050],  # 16 Ring Tip
    [-0.335, -0.648,  0.000],  # 17 Pinky MCP
    [-0.335, -0.888, -0.015],  # 18 Pinky PIP
    [-0.335, -1.058, -0.028],  # 19 Pinky DIP
    [-0.335, -1.220, -0.040],  # 20 Pinky Tip
], dtype=np.float32)

FIST = np.array([
    [ 0.000,  0.000,  0.000],  # 0  Wrist
    [ 0.275, -0.195,  0.025],  # 1  Thumb CMC
    [ 0.365, -0.310,  0.060],  # 2  Thumb MCP (pulled in)
    [ 0.305, -0.405,  0.115],  # 3  Thumb IP
    [ 0.270, -0.490,  0.145],  # 4  Thumb Tip (resting over knuckles)
    [ 0.215, -0.760,  0.000],  # 5  Index MCP
    [ 0.170, -0.895,  0.100],  # 6  Index PIP (curling forward)
    [ 0.125, -0.818,  0.175],  # 7  Index DIP
    [ 0.105, -0.710,  0.210],  # 8  Index Tip
    [ 0.018, -0.815,  0.000],  # 9  Middle MCP
    [-0.025, -0.950,  0.100],  # 10 Middle PIP
    [-0.065, -0.870,  0.175],  # 11 Middle DIP
    [-0.085, -0.755,  0.210],  # 12 Middle Tip
    [-0.175, -0.760,  0.000],  # 13 Ring MCP
    [-0.218, -0.888,  0.095],  # 14 Ring PIP
    [-0.258, -0.808,  0.168],  # 15 Ring DIP
    [-0.278, -0.698,  0.200],  # 16 Ring Tip
    [-0.335, -0.648,  0.000],  # 17 Pinky MCP
    [-0.358, -0.765,  0.075],  # 18 Pinky PIP
    [-0.385, -0.695,  0.135],  # 19 Pinky DIP
    [-0.398, -0.615,  0.165],  # 20 Pinky Tip
], dtype=np.float32)

# Per-finger joint indices (MCP, PIP/IP, DIP, Tip)
_FINGER_JOINTS: dict[str, tuple[int, int, int, int]] = {
    "thumb":  (1, 2, 3, 4),
    "index":  (5, 6, 7, 8),
    "middle": (9, 10, 11, 12),
    "ring":   (13, 14, 15, 16),
    "pinky":  (17, 18, 19, 20),
}

# ---------------------------------------------------------------------------
# Gesture library — {gesture_name: {finger: curl_amount 0=open 1=fist}}
# ---------------------------------------------------------------------------
GESTURE_CURLS: dict[str, dict[str, float]] = {
    "open_palm":  {"thumb": 0.0, "index": 0.0, "middle": 0.0, "ring": 0.0, "pinky": 0.0},
    "fist":       {"thumb": 1.0, "index": 1.0, "middle": 1.0, "ring": 1.0, "pinky": 1.0},
    "thumbs_up":  {"thumb": 0.0, "index": 1.0, "middle": 1.0, "ring": 1.0, "pinky": 1.0},
    "peace":      {"thumb": 0.8, "index": 0.0, "middle": 0.0, "ring": 1.0, "pinky": 1.0},
    "pointing":   {"thumb": 0.6, "index": 0.0, "middle": 1.0, "ring": 1.0, "pinky": 1.0},
    "rock":       {"thumb": 0.6, "index": 0.0, "middle": 1.0, "ring": 1.0, "pinky": 0.0},
    "call_me":    {"thumb": 0.0, "index": 1.0, "middle": 1.0, "ring": 1.0, "pinky": 0.0},
    "ok":         {"thumb": 0.45,"index": 0.45,"middle": 0.0, "ring": 0.0, "pinky": 0.0},
    "three":      {"thumb": 0.85,"index": 0.0, "middle": 0.0, "ring": 0.0, "pinky": 1.0},
    "four":       {"thumb": 0.9, "index": 0.0, "middle": 0.0, "ring": 0.0, "pinky": 0.0},
    "gun":        {"thumb": 0.0, "index": 0.0, "middle": 1.0, "ring": 1.0, "pinky": 1.0},
    "pinch":      {"thumb": 0.35,"index": 0.35,"middle": 0.9, "ring": 0.9, "pinky": 0.9},
    "spiderman":  {"thumb": 0.0, "index": 0.0, "middle": 1.0, "ring": 1.0, "pinky": 0.0},
    "hand_heart": {"thumb": 0.1, "index": 0.1, "middle": 0.9, "ring": 0.9, "pinky": 0.9},
    "vulcan":     {"thumb": 0.0, "index": 0.0, "middle": 0.0, "ring": 0.0, "pinky": 0.0},
    # Dynamic gestures (use transition-based generation)
    "grab":       {"thumb": 0.9, "index": 0.9, "middle": 0.9, "ring": 0.9, "pinky": 0.9},
    "release":    {"thumb": 0.0, "index": 0.0, "middle": 0.0, "ring": 0.0, "pinky": 0.0},
    "pinch_zoom": {"thumb": 0.3, "index": 0.3, "middle": 0.8, "ring": 0.8, "pinky": 0.8},
    "swipe_left": {"thumb": 0.0, "index": 0.0, "middle": 0.0, "ring": 0.0, "pinky": 0.0},
    "swipe_right":{"thumb": 0.0, "index": 0.0, "middle": 0.0, "ring": 0.0, "pinky": 0.0},
}

# Gesture pairs that transition into each other (for dynamic sequence generation)
_TRANSITIONS: dict[str, tuple[str, str]] = {
    "grab":       ("open_palm", "fist"),
    "release":    ("fist", "open_palm"),
    "pinch_zoom": ("pinch", "open_palm"),
    "swipe_left": ("open_palm", "open_palm"),  # same pose, hand translates
    "swipe_right":("open_palm", "open_palm"),
}

GESTURE_NAMES: list[str] = sorted(GESTURE_CURLS.keys())


# ---------------------------------------------------------------------------
# Pose construction
# ---------------------------------------------------------------------------

def _make_pose(curls: dict[str, float]) -> np.ndarray:
    """Build a [21, 3] pose by interpolating each finger between open and fist."""
    pose = OPEN_PALM.copy()
    for finger, curl in curls.items():
        for joint_idx in _FINGER_JOINTS[finger][1:]:  # skip MCP
            pose[joint_idx] = (1.0 - curl) * OPEN_PALM[joint_idx] + curl * FIST[joint_idx]
    return pose


def _pose_to_vector(pose: np.ndarray) -> np.ndarray:
    """Flatten [21, 3] → [63] (the format FeatureExtractor.extract_coordinates outputs)."""
    return pose.flatten()


# ---------------------------------------------------------------------------
# Ornstein-Uhlenbeck noise — correlated random walk for natural tremor
# ---------------------------------------------------------------------------

def _ou_noise(
    shape: tuple,
    rng: np.random.Generator,
    theta: float = 0.3,
    sigma: float = 0.012,
) -> np.ndarray:
    """Generate Ornstein-Uhlenbeck correlated noise of given shape."""
    n = shape[0]
    x = np.zeros(shape, dtype=np.float32)
    for t in range(1, n):
        x[t] = x[t - 1] * (1.0 - theta) + rng.standard_normal(shape[1:]).astype(np.float32) * sigma
    return x


# ---------------------------------------------------------------------------
# Random 3-D rotation helpers
# ---------------------------------------------------------------------------

def _rot_x(a: float) -> np.ndarray:
    return np.array([[1, 0, 0], [0, np.cos(a), -np.sin(a)], [0, np.sin(a), np.cos(a)]], dtype=np.float32)

def _rot_y(a: float) -> np.ndarray:
    return np.array([[np.cos(a), 0, np.sin(a)], [0, 1, 0], [-np.sin(a), 0, np.cos(a)]], dtype=np.float32)

def _rot_z(a: float) -> np.ndarray:
    return np.array([[np.cos(a), -np.sin(a), 0], [np.sin(a), np.cos(a), 0], [0, 0, 1]], dtype=np.float32)


def _random_rotation(rng: np.random.Generator, max_deg: float = 45.0) -> np.ndarray:
    """Random rotation matrix drawn uniformly up to max_deg on each axis."""
    r = np.deg2rad(max_deg)
    ax = rng.uniform(-r, r)
    ay = rng.uniform(-r, r)
    az = rng.uniform(-r * 0.5, r * 0.5)
    return _rot_x(ax) @ _rot_y(ay) @ _rot_z(az)


# ---------------------------------------------------------------------------
# Sequence generation
# ---------------------------------------------------------------------------

def generate_sequence(
    gesture_name: str,
    seq_len: int = 32,
    rng: np.random.Generator | None = None,
    rotation_range_deg: float = 45.0,
    tremor_sigma: float = 0.012,
    scale_range: tuple[float, float] = (0.85, 1.15),
    curl_noise: float = 0.06,
) -> np.ndarray:
    """Generate one synthetic gesture sequence of shape [seq_len, 63].

    Each call applies different random augmentations so repeated calls with
    the same gesture_name produce distinct training samples.
    """
    if rng is None:
        rng = np.random.default_rng()

    curls = GESTURE_CURLS[gesture_name].copy()

    # --- add per-sample variation to curl amounts --------------------------
    varied_curls = {
        finger: float(np.clip(c + rng.uniform(-curl_noise, curl_noise), 0.0, 1.0))
        for finger, c in curls.items()
    }

    # --- determine if this is a dynamic (transitioning) gesture -------------
    if gesture_name in _TRANSITIONS:
        start_name, end_name = _TRANSITIONS[gesture_name]
        start_curls = {
            f: float(np.clip(GESTURE_CURLS[start_name][f] + rng.uniform(-curl_noise, curl_noise), 0.0, 1.0))
            for f in GESTURE_CURLS[start_name]
        }
        end_curls = {
            f: float(np.clip(GESTURE_CURLS[end_name][f] + rng.uniform(-curl_noise, curl_noise), 0.0, 1.0))
            for f in GESTURE_CURLS[end_name]
        }
        start_pose = _make_pose(start_curls)
        end_pose   = _make_pose(end_curls)

        # sigmoid-shaped transition (slow-fast-slow)
        t_vals = np.linspace(-6, 6, seq_len)
        t_vals = 1.0 / (1.0 + np.exp(-t_vals))   # [0..1] sigmoid

        # optional: randomize transition phase (not always 0→1 over full seq)
        phase_shift = rng.uniform(-0.3, 0.3)
        t_vals = np.clip(t_vals + phase_shift, 0.0, 1.0)

        frames = np.array([
            (1.0 - t) * start_pose + t * end_pose
            for t in t_vals
        ], dtype=np.float32)  # [T, 21, 3]

        # Swipe gestures: add lateral translation
        if gesture_name in ("swipe_left", "swipe_right"):
            direction = -1.0 if gesture_name == "swipe_left" else 1.0
            x_shift = np.linspace(0, direction * 0.5, seq_len)[:, None, None]
            frames[:, :, 0:1] += x_shift
    else:
        base_pose = _make_pose(varied_curls)
        frames = np.tile(base_pose[np.newaxis], (seq_len, 1, 1))  # [T, 21, 3]

    # --- global random rotation (same for all frames — hand orientation) ---
    R = _random_rotation(rng, rotation_range_deg)
    frames = frames @ R.T  # [T, 21, 3]

    # --- random uniform scale (palm size variation) -------------------------
    scale = rng.uniform(*scale_range)
    frames *= scale

    # --- Ornstein-Uhlenbeck tremor per joint per axis -----------------------
    tremor = _ou_noise((seq_len, 21, 3), rng, sigma=tremor_sigma)
    frames += tremor

    # --- slow global rotation drift (hand moves slightly during hold) -------
    drift_amp = rng.uniform(0.0, 0.04)
    drift_ax = rng.uniform(-1, 1, 3)
    drift_ax = drift_ax / (np.linalg.norm(drift_ax) + 1e-8)
    for t in range(seq_len):
        drift_angle = drift_amp * np.sin(np.pi * t / seq_len)
        # Rodrigues rotation formula (small angle: approx Identity + skew-sym)
        K = np.array([
            [0,          -drift_ax[2], drift_ax[1]],
            [drift_ax[2], 0,          -drift_ax[0]],
            [-drift_ax[1], drift_ax[0], 0],
        ], dtype=np.float32)
        R_drift = np.eye(3, dtype=np.float32) + np.sin(drift_angle) * K + (1 - np.cos(drift_angle)) * (K @ K)
        frames[t] = frames[t] @ R_drift.T

    # --- random speed perturbation (variable-tempo sequences) ---------------
    if seq_len >= 8 and rng.uniform() < 0.5:
        speed = rng.uniform(0.6, 1.4)
        orig_len = int(seq_len * speed)
        orig_len = max(4, min(seq_len * 2, orig_len))
        # Resample to orig_len then re-interpolate back to seq_len
        t_orig = np.linspace(0, 1, orig_len)
        t_target = np.linspace(0, 1, seq_len)
        resampled = np.zeros((seq_len, 21, 3), dtype=np.float32)
        for j in range(21):
            for c in range(3):
                resampled[:, j, c] = np.interp(t_target, t_orig,
                    np.interp(t_orig, np.linspace(0, 1, seq_len), frames[:, j, c]))
        frames = resampled

    # --- flatten [T, 21, 3] → [T, 63] --------------------------------------
    return frames.reshape(seq_len, 63).astype(np.float32)
